# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.box = "hashicorp/precise64"
  
  config.vm.hostname = "SpyRuntime"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    # vb.gui = true
    # Customize the amount of memory on the VM:
    vb.memory = "1024"
	vb.name = "SpyRuntime"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
	sudo apt-get install -y ubuntu-desktop
	sudo wget --no-check-certificate https://github.com/aglover/ubuntu-equip/raw/master/equip_java8.sh && bash equip_java8.sh
	useradd -m -s /bin/bash -U SpyRuntime
  SHELL
end

